version: '2'
services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=kallithea_user
      - POSTGRES_PASSWORD=kallithea_secret
      - POSTGRES_DB=kallithea_store

  app:
    image: toras9000/kallithea:gu
    build: ./build
    restart: always
    links:
      - db:db-container
    ports:
      - "8000:80"
    volumes:
      - ./volumes/app/config:/kallithea/config
      - ./volumes/app/repos:/kallithea/repos
      - ./volumes/app/logs:/kallithea/logs
    environment:
      - KALLITHEA_EXTERNAL_DB=postgres://kallithea_user:kallithea_secret@db-container/kallithea_store
      - KALLITHEA_ADMIN_USER=admin
      - KALLITHEA_ADMIN_PASS=admin123
      - KALLITHEA_ADMIN_MAIL=admin@example.com
      - KALLITHEA_LANG=ja
      - KALLITHEA_LOCALE=ja_JP.UTF-8
      - KALLITHEA_REPOSORT_IDX=4
      - KALLITHEA_REPOSORT_ORDER=desc
      - KALLITHEA_FIX_PERMISSION=true
